services:
  banking_system.infrastructure.api:
    image: banking_system.infrastructure.api
    build:
      context: .
      dockerfile: BankingSystem.Infrastructure/BankingSystem.Infrastructure.Api/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres_db
  
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2404
      POSTGRES_DB: banking_system
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: